# Generated by Django 3.1.3 on 2021-01-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Введите город', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(help_text='Введите название вакансии', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyDescribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_of_vacancy', models.TextField(help_text='Введите описание', max_length=50000)),
                ('skills_and_experience', models.CharField(help_text='Требуемые навыки и опыт', max_length=1000)),
                ('vacancy_title', models.OneToOneField(help_text='Название вакансии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.ManyToManyField(help_text='Choose vacancy', to='catalog.VacancyName'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_desc',
            field=models.ForeignKey(help_text='Описанте вакансии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vacancydescribe'),
        ),
    ]
