# Generated by Django 3.1.3 on 2021-01-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancydescribe',
            name='vacancy_title',
            field=models.OneToOneField(help_text='Название вакансии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vacancyname'),
        ),
    ]
