# Generated by Django 3.1.3 on 2021-01-13 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210113_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='name',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.OneToOneField(help_text='Choose vacancy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vacancyname'),
        ),
    ]
