# Generated by Django 3.1.3 on 2021-01-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210113_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.ForeignKey(help_text='Введите название вакансии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vacancyname'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_desc',
            field=models.ForeignKey(help_text='Описание вакансии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vacancydescribe'),
        ),
    ]
