# Generated by Django 3.1.3 on 2021-01-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210119_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='name',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.ManyToManyField(help_text='Выберите название вакансии', to='catalog.VacancyName'),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_desc',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_desc',
            field=models.ManyToManyField(help_text='Описание вакансии', to='catalog.VacancyDescribe'),
        ),
        migrations.AlterField(
            model_name='vacancydescribe',
            name='vacancy_title',
            field=models.ForeignKey(help_text='Название вакансии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vacancyname'),
        ),
    ]
