# Generated by Django 3.1.3 on 2021-01-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210119_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='details',
            field=models.TextField(default=1, help_text='Описание вакансии', max_length=50000),
            preserve_default=False,
        ),
    ]
